### ISSUE TITLE
add some example

### ISSUE THREAD

**Issue by takeoffstd** [EmbersArc/SuccessiveConvexificationCpp#14]
Hi, Sven. 
Could you add some example ,such as differential drive robot example ,just like your SCvx project ?

Hope for replies, thanks.

**Comment by EmbersArc** [comment]
Hi! There are three existing models already. The 2D rocket one is the easiest if you want to learn how they can be implemented. I am not planning on adding a diffdrive model since there are better algorithms for those kinds of problems. But feel free to ask any questions about how to implement a specific model.
